Reverted some temporary changes

diff --git a/.github/workflows/acceptance-test.yml b/.github/workflows/acceptance-test.yml
--- a/.github/workflows/acceptance-test.yml
+++ b/.github/workflows/acceptance-test.yml
@@ -25,6 +25,12 @@ jobs:
               export TESTCOV_THRESHOLD=50
               echo "Threshold: $TESTCOV_THRESHOLD %"
               totalCoverage=`go tool cover -func=c.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
-              echo `git branch | grep "\*"`
-              exit 1
+              echo "Current test coverage : $totalCoverage %"
+              if (( $(echo "$totalCoverage $TESTCOV_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                  echo "Coverage passed"
+              else
+                  echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+                  echo "Coverage check failed"
+                  exit 1
+              fi
       - run: echo "🍏 This job's status is ${{ job.status }}."
